services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: kapasity-go-image:latest  # Define the image name and tag here
    container_name: kapasity_go_backend_prod
    ports:
      - "8060:8000"
    env_file:
      - .env.prod
    networks:
      - devices_network  # Add the network

networks:
  devices_network:
    external: true  # Declare the network as external